% Make a table to analyze time of the second response
% clear all
% close all 
% clc
% load('EEG_epoch_raw_new')
EVENT = 2; RESP = 3; TMP = 4; DELAY = 5; RESP2 = 6; DELAY2 = 7; 

delaystat = [];

for user = task.codeUsers
    idx1 = find(user == dataY(:,1) & ...
        1 == dataY(:,RESP) & ...
        11 == dataY(:,RESP2));
    del1 = mean(dataY(idx1,DELAY) - dataY(idx1,DELAY2));
    disp(['User: ', num2str(user), '  1->11 changes: '  num2str(size(idx1,1))]);
        idx2 = find(user == dataY(:,1) & ...
        11 == dataY(:,RESP) & ...
        1 == dataY(:,RESP2));
        del2 = mean(dataY(idx2,DELAY) - dataY(idx2,DELAY2));
    disp(['User: ', num2str(user), '  11->1 changes: '  num2str(size(idx2,1))]);
    idx3 = find(user == dataY(:,1) & ...
        2 == dataY(:,RESP) & ...
        12 == dataY(:,RESP2));
    del3 = mean(dataY(idx3,DELAY) - dataY(idx3,DELAY2));
    disp(['User: ', num2str(user), '  2->12 changes: '  num2str(size(idx3,1))]);
    idx4 = find(user == dataY(:,1) & ...
        12 == dataY(:,RESP) & ...
        2 == dataY(:,RESP2));
    del4 = mean(dataY(idx4,DELAY) - dataY(idx4,DELAY2));
    disp(['User: ', num2str(user), '  12->2 changes: '  num2str(size(idx4,1))]);
    
delaystat(end+1,:) = [user, ...
    size(find(user == dataY(:,1))),... % number of events
    size(idx1,1),...
    -1* del1,...
    size(idx2,1),...
    -1* del2,...
    size(idx3,1),...
    -1* del3,...
    size(idx4,1),...
    -1* del4,...    
    ];
% CONCLUSION
% SEE table delaystat


